name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      pull-requests: write
      issues: write

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_BACKEND_REGION }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init \
              -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
              -backend-config="key=${{ secrets.TF_BACKEND_KEY }}" \
              -backend-config="region=${{ secrets.TF_BACKEND_REGION }}"

      # Terraform Plan
      - name: Terraform Plan
        id: tf_plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      # Show the plan output for review
      - name: Post plan status
        if: failure() || success()
        run: echo "Plan output status: $?"

      # Require manual approval for apply step
      - name: Manual Approval Required
        if: success() && github.event_name == 'pull_request'
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: "pr"
          commands: "/approve"
          permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Wait for manual approval
      - name: Wait for approval
        if: success() && github.event_name == 'pull_request'
        uses: ahmadnassri/action-await-approval@v1
        with:
          approvers: 'team1'  # Specify the GitHub user/team that must approve
          comment: 'Please review and approve the changes'

      # Apply Terraform only after manual approval
      - name: Terraform Apply
        if: success() && github.event_name == 'pull_request'
        run: terraform apply "tfplan"
