name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      pull-requests: write
      issues: write

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_BACKEND_REGION }}

  # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        id: tf_plan
        run: terraform plan -out=tfplan

      # Show the plan output for review
      - name: Post plan status
        if: failure() || success()
        run: echo "Plan output status: $?"

      # Require manual approval for apply step
      - name: Manual Approval Required
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const approvalMessage = 'Please review and approve the changes';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: approvalMessage
            });
            core.setFailed('Waiting for approval');

      # Wait for manual approval
      - name: Wait for approval
        if: success() && github.event_name == 'pull_request'
        uses: ahmadnassri/action-await-approval@v1
        with:
          approvers: 'team1'
          comment: 'Approved by the team'

      # Apply Terraform only after manual approval
      - name: Terraform Apply
        if: success() && github.event_name == 'pull_request'
        run: terraform apply "tfplan"
