name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      pull-requests: write
      issues: write

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_BACKEND_REGION }}

  # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        id: tf_plan
        run: terraform plan -out=tfplan

      # Show the plan output for review
      - name: Terraform Plan Status
        if: failure() || success()
        run: echo "Plan completed with status $?"

  approval:
    name: Manual Approval
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: production
      # Requires a manual approval if environment protection rules are enabled

    steps:
      - name: Wait for manual approval
        run: echo "Waiting for manual approval to proceed"

  apply:
    name: Terraform Apply
    needs: approval
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again in this job
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply "tfplan"
