name: Terraform Apply

on:
  push:
    branches:
      - main
      - dev
      - staging
      - production
  pull_request:
    branches:
      - main
      - dev
      - staging
      - production    

jobs:
  apply:
    name: Terraform Apply ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write

    env:
      TF_VERSION: ${{ secrets.TF_VERSION }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_PLAN_CACHE: terraform.tfplan
      AWS_ROLE: ${{ secrets.AWS_ROLE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: us-east-1

      - name: Debug Info
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Pull Request ID: ${{ github.event.pull_request.number }}"
          echo "AWS_ACCOUNT: ${{ env.AWS_ACCOUNT }}"
          echo "AWS_ROLE: ${{ env.AWS_ROLE }}"
          echo "Terraform Version: ${{ env.TF_VERSION }}"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        run: |
          terraform plan

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.G_TOKEN }}
          approvers: yahyagulshan, yahyaawan
          minimum-approvals: 1
          issue-title: "Pull Request ID: ${{ github.event.pull_request.number }}"
          issue-body: "Branch name: ${{ github.head_ref }}"
          exclude-workflow-initiator-as-approver: false
          
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
